name: alarm_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.15
  path: ^1.8.3
  intl: ^0.18.1
  android_alarm_manager_plus: ^3.0.0
  flutter_local_notifications: ^15.1.0+1
  vibration: ^1.7.6
  permission_handler: ^10.2.0
  file_picker: ^5.3.0
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.9.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
