name: alarm_app
description: A native-like alarm clock application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # UI dependencies
  cupertino_icons: ^1.0.2

  # Alarm scheduling
  android_alarm_manager_plus: ^3.0.4

  # Local notifications
  flutter_local_notifications: ^17.0.0

  # Permission handling
  permission_handler: ^11.1.0

  # Timezone support
  timezone: ^0.9.2

  # Persistent storage
  shared_preferences: ^2.2.2

  # Audio playback
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
